### Práctica 7 - 5 Peticiones de Miembros
@host = http://localhost:3000

### 1. Método: listar() -> 200
GET {{host}}/miembros


### 2. Método: buscar() -> 200
### Busca al primer miembro del repositorio en memoria
GET {{host}}/miembros/1


### 3. Método: crear() -> 201
### Crea un cuarto miembro en el arreglo (se le asignará el ID 4)
POST {{host}}/miembros
Content-Type: application/json

{
  "nombre": "Pedro",
  "correo": "pedro@test.com",
  "membresia": "Mensual"
}


### 4. Método: actualizar() -> 200
### Modifica al miembro que se acaba de crear en el paso anterior (ID 4)
PATCH {{host}}/miembros/4
Content-Type: application/json

{
  "membresia": "Anual",
  "activo": false
}


### 5. Método: eliminar() -> 200
### Elimina al miembro creado (ID 4)
DELETE {{host}}/miembros/4